import { Quiz } from "./Types";
export const Data: Quiz[] = [
  {
    id: 0,
    genre: "Alternative Rock",
    question: "What year did Radiohead release their album 'OK Computer'?",
    answers: ["1997", "1995", "1999"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 1,
    genre: "Shoegaze",
    question: "Which band is considered a pioneer of the Shoegaze genre?",
    answers: ["The Cure", "Slowdive", "My Bloody Valentine"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 2,
    genre: "Experimental",
    question: "Which artist is known for the experimental album 'Biophilia'?",
    answers: ["Björk", "Aphex Twin", "Brian Eno"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 3,
    genre: "Indie Rock",
    question: "Which band released the album 'Funeral' in 2004?",
    answers: ["The Strokes", "Arcade Fire", "Vampire Weekend"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 4,
    genre: "Psychedelia",
    question:
      "Which Pink Floyd album features the track 'Interstellar Overdrive'?",
    answers: [
      "The Piper at the Gates of Dawn",
      "Dark Side of the Moon",
      "Meddle",
    ],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 5,
    genre: "Punk",
    question: "Which iconic punk album features the track 'Guns of Brixton'?",
    answers: ["Never Mind the Bollocks", "London Calling", "Rocket to Russia"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 6,
    genre: "Post Punk",
    question:
      "Which band's music video for 'Once in a Lifetime' became an MTV classic?",
    answers: ["The Smiths", "Talking Heads", "Joy Division"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 7,
    genre: "New Wave",
    question: "Which band is known for the song 'Whip It'?",
    answers: ["New Order", "Devo", "The B-52's"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 8,
    genre: "Prog Rock",
    question: "Which progressive rock album features the track 'Roundabout'?",
    answers: ["Fragile", "Selling England by the Pound", "Aqualung"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 9,
    genre: "Electronic",
    question: "Who is known for the influential electronic track 'Autobahn'?",
    answers: ["Kraftwerk", "Daft Punk", "Underworld"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 10,
    genre: "Alternative Rock",
    question: "Which Pixies song features the iconic lyric 'Where is my mind?'",
    answers: ["Here Comes Your Man", "Gigantic", "Where Is My Mind?"],
    correctAnswer: 2,
    difficulty: "Easy",
  },
  {
    id: 11,
    genre: "Shoegaze",
    question: "Which band's debut album includes the track 'Catch the Breeze'?",
    answers: ["Ride", "Slowdive", "Lush"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 12,
    genre: "Ambient",
    question:
      "Which artist pioneered the genre with the album 'Music for Airports'?",
    answers: ["Brian Eno", "Philip Glass", "Steve Reich"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 13,
    genre: "Indie Rock",
    question: "Which band has the song 'PDA' on their debut album?",
    answers: ["Interpol", "The National", "Arcade Fire"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 14,
    genre: "Psychedelia",
    question:
      "Which band's psychedelic rock track 'Time of the Season' became a hit?",
    answers: ["The Zombies", "The Byrds", "The Rolling Stones"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 15,
    genre: "Punk",
    question: "Who is the lead vocalist of the punk band Dead Kennedys?",
    answers: ["Johnny Rotten", "Joe Strummer", "Jello Biafra"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 16,
    genre: "Post Punk",
    question: "Which band released the influential album 'Entertainment!'?",
    answers: ["Siouxsie and the Banshees", "Wire", "Gang of Four"],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 17,
    genre: "New Wave",
    question: "Which band released the album 'Remain in Light'?",
    answers: ["Blondie", "Talking Heads", "The B-52's"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 18,
    genre: "Prog Rock",
    question: "Which band is known for the epic track 'Supper's Ready'?",
    answers: ["Genesis", "Yes", "King Crimson"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 19,
    genre: "Electronic",
    question:
      "Which artist's album 'Selected Ambient Works 85-92' is highly influential?",
    answers: ["Aphex Twin", "Orbital", "The Chemical Brothers"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 20,
    genre: "Alternative Rock",
    question:
      "Which band's lead singer wrote the memoir 'Glorious Rock Bottom'?",
    answers: ["Elliott Smith", "Neutral Milk Hotel", "Marina and the Diamonds"],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 21,
    genre: "Shoegaze",
    question: "Which band's debut album is titled 'Just for a Day'?",
    answers: ["Slowdive", "Lush", "Chapterhouse"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 22,
    genre: "Indie Rock",
    question: "Which album by The Shins features the song 'New Slang'?",
    answers: [
      "Oh, Inverted World",
      "Chutes Too Narrow",
      "Wincing the Night Away",
    ],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 23,
    genre: "Psychedelia",
    question: "Which band released the album 'Forever Changes'?",
    answers: ["The Doors", "Love", "Jefferson Airplane"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 24,
    genre: "Punk",
    question:
      "Which punk band released the album 'Fresh Fruit for Rotting Vegetables'?",
    answers: ["The Damned", "The Misfits", "Dead Kennedys"],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 25,
    genre: "Post Punk",
    question: "Which album is considered a seminal work in post-punk?",
    answers: ["Closer", "Seventeen Seconds", "Marquee Moon"],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 26,
    genre: "New Wave",
    question: "Which band released the song 'Heart of Glass'?",
    answers: ["Talking Heads", "Blondie", "The Cars"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 27,
    genre: "Prog Rock",
    question:
      "Which band released the concept album 'The Lamb Lies Down on Broadway'?",
    answers: ["Genesis", "Pink Floyd", "Jethro Tull"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 28,
    genre: "Electronic",
    question: "Which album by Daft Punk is known for the hit 'One More Time'?",
    answers: ["Discovery", "Random Access Memories", "Homework"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
];
