import { Quiz } from "./Types";
export const Data: Quiz[] = [
  {
    id: 0,
    genre: "Alternative Rock",
    question: "What year did Radiohead release their album 'OK Computer'?",
    answers: ["1997", "1995", "1999"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 1,
    genre: "Shoegaze",
    question: "Which band is considered a pioneer of the Shoegaze genre?",
    answers: ["The Cure", "Slowdive", "My Bloody Valentine"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 2,
    genre: "Experimental",
    question: "Which artist is known for the experimental album 'Biophilia'?",
    answers: ["Björk", "Aphex Twin", "Brian Eno"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 3,
    genre: "Indie Rock",
    question: "Which band released the album 'Funeral' in 2004?",
    answers: ["The Strokes", "Arcade Fire", "Vampire Weekend"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 4,
    genre: "Psychedelia",
    question:
      "Which Pink Floyd album features the track 'Interstellar Overdrive'?",
    answers: [
      "The Piper at the Gates of Dawn",
      "Dark Side of the Moon",
      "Meddle",
    ],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 5,
    genre: "Punk",
    question: "Which iconic punk album features the track 'Guns of Brixton'?",
    answers: ["Never Mind the Bollocks", "London Calling", "Rocket to Russia"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 6,
    genre: "Post Punk",
    question:
      "Which band's music video for 'Once in a Lifetime' became an MTV classic?",
    answers: ["The Smiths", "Talking Heads", "Joy Division"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 7,
    genre: "New Wave",
    question: "Which band is known for the song 'Whip It'?",
    answers: ["New Order", "Devo", "The B-52's"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 8,
    genre: "Prog Rock",
    question: "Which progressive rock album features the track 'Roundabout'?",
    answers: ["Fragile", "Selling England by the Pound", "Aqualung"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 9,
    genre: "Electronic",
    question: "Who is known for the influential electronic track 'Autobahn'?",
    answers: ["Kraftwerk", "Daft Punk", "Underworld"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 10,
    genre: "Alternative Rock",
    question: "Which Pixies song features the iconic lyric 'Where is my mind?'",
    answers: ["Here Comes Your Man", "Gigantic", "Where Is My Mind?"],
    correctAnswer: 2,
    difficulty: "Easy",
  },
  {
    id: 11,
    genre: "Shoegaze",
    question: "Which band's debut album includes the track 'Catch the Breeze'?",
    answers: ["Ride", "Slowdive", "Lush"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 12,
    genre: "Ambient",
    question:
      "Which artist pioneered the genre with the album 'Music for Airports'?",
    answers: ["Brian Eno", "Philip Glass", "Steve Reich"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 13,
    genre: "Indie Rock",
    question: "Which band has the song 'PDA' on their debut album?",
    answers: ["Interpol", "The National", "Arcade Fire"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 14,
    genre: "Psychedelia",
    question:
      "Which band's psychedelic rock track 'Time of the Season' became a hit?",
    answers: ["The Zombies", "The Byrds", "The Rolling Stones"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 15,
    genre: "Punk",
    question: "Who is the lead vocalist of the punk band Dead Kennedys?",
    answers: ["Johnny Rotten", "Joe Strummer", "Jello Biafra"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 16,
    genre: "Post Punk",
    question: "Which band released the influential album 'Entertainment!'?",
    answers: ["Siouxsie and the Banshees", "Wire", "Gang of Four"],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 17,
    genre: "New Wave",
    question: "Which band released the album 'Remain in Light'?",
    answers: ["Blondie", "Talking Heads", "The B-52's"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 18,
    genre: "Prog Rock",
    question: "Which band is known for the epic track 'Supper's Ready'?",
    answers: ["Genesis", "Yes", "King Crimson"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 19,
    genre: "Electronic",
    question:
      "Which artist's album 'Selected Ambient Works 85-92' is highly influential?",
    answers: ["Aphex Twin", "Orbital", "The Chemical Brothers"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 20,
    genre: "Alternative Rock",
    question:
      "Which band's lead singer wrote the memoir 'Glorious Rock Bottom'?",
    answers: ["Elliott Smith", "Neutral Milk Hotel", "Marina and the Diamonds"],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 21,
    genre: "Shoegaze",
    question: "Which band's debut album is titled 'Just for a Day'?",
    answers: ["Slowdive", "Lush", "Chapterhouse"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 22,
    genre: "Indie Rock",
    question: "Which album by The Shins features the song 'New Slang'?",
    answers: [
      "Oh, Inverted World",
      "Chutes Too Narrow",
      "Wincing the Night Away",
    ],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 23,
    genre: "Psychedelia",
    question: "Which band released the album 'Forever Changes'?",
    answers: ["The Doors", "Love", "Jefferson Airplane"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 24,
    genre: "Punk",
    question:
      "Which punk band released the album 'Fresh Fruit for Rotting Vegetables'?",
    answers: ["The Damned", "The Misfits", "Dead Kennedys"],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 25,
    genre: "Post Punk",
    question: "Which album is considered a seminal work in post-punk?",
    answers: ["Closer", "Seventeen Seconds", "Marquee Moon"],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 26,
    genre: "New Wave",
    question: "Which band released the song 'Heart of Glass'?",
    answers: ["Talking Heads", "Blondie", "The Cars"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 27,
    genre: "Prog Rock",
    question:
      "Which band released the concept album 'The Lamb Lies Down on Broadway'?",
    answers: ["Genesis", "Pink Floyd", "Jethro Tull"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 28,
    genre: "Electronic",
    question: "Which album by Daft Punk is known for the hit 'One More Time'?",
    answers: ["Discovery", "Random Access Memories", "Homework"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 29,
    genre: "Alternative Rock",
    question: "Which band's album 'In Utero' was released in 1993?",
    answers: ["Nirvana", "Pearl Jam", "Soundgarden"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 30,
    genre: "Shoegaze",
    question:
      "Which album by My Bloody Valentine is considered a shoegaze classic?",
    answers: ["Souvlaki", "Loveless", "Heaven or Las Vegas"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 31,
    genre: "Experimental",
    question: "Which album by Aphex Twin features the track 'Windowlicker'?",
    answers: [
      "Richard D. James Album",
      "Selected Ambient Works Volume II",
      "Come to Daddy",
    ],
    correctAnswer: 2,
    difficulty: "Hard",
  },
  {
    id: 32,
    genre: "Indie Rock",
    question: "Which band released the song 'Mr. Brightside'?",
    answers: ["The Killers", "Franz Ferdinand", "The Arctic Monkeys"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 33,
    genre: "Psychedelia",
    question: "Which band is known for the song 'White Rabbit'?",
    answers: ["Jefferson Airplane", "The Grateful Dead", "The Byrds"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 34,
    genre: "Punk",
    question: "Which band released the album 'Damaged' in 1981?",
    answers: ["Black Flag", "Minor Threat", "Bad Brains"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 35,
    genre: "Post Punk",
    question: "Which band is known for the song 'A Forest'?",
    answers: ["Joy Division", "The Cure", "Siouxsie and the Banshees"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 36,
    genre: "New Wave",
    question: "Which band had a hit with the song 'Tainted Love'?",
    answers: ["Depeche Mode", "Soft Cell", "Human League"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 37,
    genre: "Prog Rock",
    question:
      "Which band released the album 'In the Court of the Crimson King'?",
    answers: ["King Crimson", "Yes", "Genesis"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 38,
    genre: "Electronic",
    question:
      "Which album by The Chemical Brothers features the track 'Hey Boy Hey Girl'?",
    answers: ["Dig Your Own Hole", "Surrender", "Exit Planet Dust"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 39,
    genre: "Alternative Rock",
    question: "Which band released the album 'Doolittle' in 1989?",
    answers: ["The Smashing Pumpkins", "Pixies", "Sonic Youth"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 40,
    genre: "Shoegaze",
    question: "Which band is known for the song 'Pearl'?",
    answers: ["Ride", "Lush", "Slowdive"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 41,
    genre: "Ambient",
    question:
      "Which artist created the ambient series 'Selected Ambient Works'?",
    answers: ["Aphex Twin", "Brian Eno", "Moby"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 42,
    genre: "Indie Rock",
    question: "Which band's debut album is titled 'Turn On the Bright Lights'?",
    answers: ["The Strokes", "Interpol", "Arctic Monkeys"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 43,
    genre: "Psychedelia",
    question: "Which band is known for the album 'Disraeli Gears'?",
    answers: ["Cream", "The Jimi Hendrix Experience", "The Doors"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 44,
    genre: "Punk",
    question: "Which band released the song 'Holiday in Cambodia'?",
    answers: ["The Clash", "Dead Kennedys", "Ramones"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 45,
    genre: "Post Punk",
    question: "Which band is known for the song 'Atmosphere'?",
    answers: ["Joy Division", "The Cure", "Public Image Ltd"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 46,
    genre: "New Wave",
    question: "Which band released the song 'Love Will Tear Us Apart'?",
    answers: ["New Order", "Joy Division", "The Smiths"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 47,
    genre: "Prog Rock",
    question: "Which band is known for the album 'Aqualung'?",
    answers: ["Jethro Tull", "Pink Floyd", "Emerson, Lake & Palmer"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 48,
    genre: "Electronic",
    question: "Which band released the album 'Homework'?",
    answers: ["Daft Punk", "Underworld", "Chemical Brothers"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 49,
    genre: "Alternative Rock",
    question: "Which band is known for the song 'Creep'?",
    answers: ["Nirvana", "Radiohead", "Pearl Jam"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 50,
    genre: "Alternative Rock",
    question:
      "Which band released the album 'Mellon Collie and the Infinite Sadness'?",
    answers: ["Nirvana", "The Smashing Pumpkins", "Pearl Jam"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 51,
    genre: "Shoegaze",
    question: "Which band is known for the song 'Vapour Trail'?",
    answers: ["My Bloody Valentine", "Ride", "Chapterhouse"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 52,
    genre: "Experimental",
    question: "Which artist released the album 'Kid A'?",
    answers: ["Radiohead", "Björk", "Aphex Twin"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 53,
    genre: "Indie Rock",
    question: "Which band released the song 'Electric Feel'?",
    answers: ["MGMT", "The Strokes", "Arctic Monkeys"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 54,
    genre: "Psychedelia",
    question:
      "Which band is known for the song 'Lucy in the Sky with Diamonds'?",
    answers: ["The Beatles", "The Byrds", "The Rolling Stones"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 55,
    genre: "Punk",
    question: "Which band released the album 'Never Mind the Bollocks'?",
    answers: ["The Clash", "The Ramones", "Sex Pistols"],
    correctAnswer: 2,
    difficulty: "Easy",
  },
  {
    id: 56,
    genre: "Post Punk",
    question: "Which band is known for the song 'Shadowplay'?",
    answers: ["Joy Division", "The Cure", "Echo & the Bunnymen"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 57,
    genre: "New Wave",
    question: "Which band released the song 'Blue Monday'?",
    answers: ["Depeche Mode", "New Order", "The Human League"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 58,
    genre: "Prog Rock",
    question: "Which band released the album 'Thick as a Brick'?",
    answers: ["Yes", "King Crimson", "Jethro Tull"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 59,
    genre: "Electronic",
    question: "Which artist is known for the song 'Porcelain'?",
    answers: ["Moby", "The Chemical Brothers", "Underworld"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 60,
    genre: "Alternative Rock",
    question: "Which band released the album 'Ten'?",
    answers: ["Nirvana", "Pearl Jam", "Soundgarden"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 61,
    genre: "Shoegaze",
    question: "Which band's album is titled 'Loveless'?",
    answers: ["Lush", "My Bloody Valentine", "Ride"],
    correctAnswer: 1,
    difficulty: "Hard",
  },
  {
    id: 62,
    genre: "Ambient",
    question:
      "Which artist is known for the album 'Ambient 1: Music for Airports'?",
    answers: ["Brian Eno", "Steve Reich", "Philip Glass"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 63,
    genre: "Indie Rock",
    question: "Which band released the song 'Reptilia'?",
    answers: ["The Strokes", "Franz Ferdinand", "Bloc Party"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 64,
    genre: "Psychedelia",
    question: "Which band is known for the album 'Surrealistic Pillow'?",
    answers: ["Jefferson Airplane", "The Doors", "The Byrds"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 65,
    genre: "Punk",
    question: "Which band released the album 'Dookie'?",
    answers: ["Green Day", "The Offspring", "Rancid"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 66,
    genre: "Post Punk",
    question: "Which band is known for the album 'Unknown Pleasures'?",
    answers: ["Joy Division", "The Cure", "Public Image Ltd"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 67,
    genre: "New Wave",
    question: "Which band is known for the song 'Don't You Want Me'?",
    answers: ["New Order", "Depeche Mode", "The Human League"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 68,
    genre: "Prog Rock",
    question: "Which band released the album 'Close to the Edge'?",
    answers: ["Genesis", "Yes", "King Crimson"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 69,
    genre: "Electronic",
    question: "Which artist released the song 'Go'?",
    answers: ["Moby", "Aphex Twin", "Underworld"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 70,
    genre: "Alternative Rock",
    question: "Which band released the album 'Doolittle'?",
    answers: ["Pixies", "Nirvana", "Soundgarden"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 71,
    genre: "Shoegaze",
    question: "Which band released the album 'Souvlaki'?",
    answers: ["Ride", "Lush", "Slowdive"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 72,
    genre: "Experimental",
    question:
      "Which artist is known for the album 'Selected Ambient Works Volume II'?",
    answers: ["Brian Eno", "Aphex Twin", "Squarepusher"],
    correctAnswer: 1,
    difficulty: "Hard",
  },
  {
    id: 73,
    genre: "Indie Rock",
    question: "Which band released the song 'First Day of My Life'?",
    answers: ["Bright Eyes", "Death Cab for Cutie", "The Shins"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 74,
    genre: "Psychedelia",
    question: "Which band released the album 'Disraeli Gears'?",
    answers: ["Cream", "The Byrds", "Jefferson Airplane"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 75,
    genre: "Punk",
    question: "Which band released the song 'Blitzkrieg Bop'?",
    answers: ["Sex Pistols", "The Clash", "Ramones"],
    correctAnswer: 2,
    difficulty: "Easy",
  },
  {
    id: 76,
    genre: "Post Punk",
    question: "Which band released the album 'Metal Box'?",
    answers: ["Joy Division", "Public Image Ltd", "The Cure"],
    correctAnswer: 1,
    difficulty: "Hard",
  },
  {
    id: 77,
    genre: "New Wave",
    question: "Which band is known for the song 'Girls Just Want to Have Fun'?",
    answers: ["Blondie", "Cyndi Lauper", "The Go-Go's"],
    correctAnswer: 1,
    difficulty: "Easy",
  },
  {
    id: 78,
    genre: "Prog Rock",
    question: "Which band released the album '2112'?",
    answers: ["Yes", "Rush", "Genesis"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 79,
    genre: "Electronic",
    question: "Which artist is known for the song 'Born Slippy .NUXX'?",
    answers: ["The Chemical Brothers", "Orbital", "Underworld"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 80,
    genre: "Alternative Rock",
    question: "Which band released the album 'OK Go'?",
    answers: ["Radiohead", "OK Go", "Red Hot Chili Peppers"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 81,
    genre: "Shoegaze",
    question: "Which band is known for the song 'When the Sun Hits'?",
    answers: ["Lush", "Slowdive", "Ride"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 82,
    genre: "Ambient",
    question: "Which artist released the album 'Structures from Silence'?",
    answers: ["Brian Eno", "Steve Roach", "Robert Rich"],
    correctAnswer: 1,
    difficulty: "Hard",
  },
  {
    id: 83,
    genre: "Indie Rock",
    question: "Which band released the song 'Float On'?",
    answers: ["Modest Mouse", "The Shins", "Arcade Fire"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 84,
    genre: "Psychedelia",
    question: "Which band released the album 'Odyssey and Oracle'?",
    answers: ["The Zombies", "The Doors", "The Byrds"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 85,
    genre: "Punk",
    question: "Which band released the album 'Damned Damned Damned'?",
    answers: ["Sex Pistols", "The Damned", "The Clash"],
    correctAnswer: 1,
    difficulty: "Hard",
  },
  {
    id: 86,
    genre: "Post Punk",
    question: "Which band released the album 'Seventeen Seconds'?",
    answers: ["Joy Division", "The Cure", "Gang of Four"],
    correctAnswer: 1,
    difficulty: "Hard",
  },
  {
    id: 87,
    genre: "New Wave",
    question: "Which band released the album 'Beauty and the Beat'?",
    answers: ["The Go-Go's", "Blondie", "The B-52's"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 88,
    genre: "Prog Rock",
    question:
      "Which band released the album 'In the Court of the Crimson King'?",
    answers: ["Genesis", "King Crimson", "Yes"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 89,
    genre: "Electronic",
    question: "Which artist is known for the song 'Windowlicker'?",
    answers: ["Aphex Twin", "Underworld", "The Chemical Brothers"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 90,
    genre: "Alternative Rock",
    question: "Which band released the album 'Is This It'?",
    answers: ["The Strokes", "Interpol", "The Libertines"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 91,
    genre: "Shoegaze",
    question: "Which band released the album 'Nowhere'?",
    answers: ["Slowdive", "Ride", "My Bloody Valentine"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 92,
    genre: "Ambient",
    question:
      "Which artist released the album 'Apollo: Atmospheres and Soundtracks'?",
    answers: ["Brian Eno", "Steve Roach", "Robert Rich"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 93,
    genre: "Indie Rock",
    question: "Which band released the song 'Take Me Out'?",
    answers: ["Franz Ferdinand", "Bloc Party", "The Strokes"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 94,
    genre: "Psychedelia",
    question: "Which band is known for the song 'White Rabbit'?",
    answers: ["Jefferson Airplane", "The Byrds", "The Doors"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
  {
    id: 95,
    genre: "Punk",
    question: "Which band released the album 'Rocket to Russia'?",
    answers: ["Sex Pistols", "Ramones", "The Clash"],
    correctAnswer: 1,
    difficulty: "Medium",
  },
  {
    id: 96,
    genre: "Post Punk",
    question: "Which band released the album 'Songs of the Free'?",
    answers: ["Gang of Four", "The Cure", "Joy Division"],
    correctAnswer: 0,
    difficulty: "Hard",
  },
  {
    id: 97,
    genre: "New Wave",
    question: "Which band released the album 'Speak & Spell'?",
    answers: ["Depeche Mode", "New Order", "The Human League"],
    correctAnswer: 0,
    difficulty: "Medium",
  },
  {
    id: 98,
    genre: "Prog Rock",
    question: "Which band released the album 'Aqualung'?",
    answers: ["Yes", "Genesis", "Jethro Tull"],
    correctAnswer: 2,
    difficulty: "Medium",
  },
  {
    id: 99,
    genre: "Electronic",
    question: "Which artist is known for the song 'Around the World'?",
    answers: ["Daft Punk", "Underworld", "The Chemical Brothers"],
    correctAnswer: 0,
    difficulty: "Easy",
  },
];
